"""music init3

Revision ID: 1b97a3238621
Revises: a250f2cea9b1
Create Date: 2025-05-01 22:42:59.482443

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1b97a3238621"
down_revision = "32656ad0b5aa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "playlist",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("discord_id", sa.VARCHAR(20), nullable=False),
        sa.Column("playlist_name", sa.VARCHAR, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("playlist_name"),
    )
    op.create_table(
        "playlistSong",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("playlist_id", sa.Integer(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "radio",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("embed_id", sa.VARCHAR(20), nullable=False),
        sa.Column("guild_id", sa.VARCHAR(20), nullable=False),
        sa.Column("channel_id", sa.VARCHAR(20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel_id"),
    )
    op.create_table(
        "song",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(), nullable=False),
        sa.Column("url", sa.VARCHAR(), nullable=False),
        sa.Column("thumbnail_url", sa.VARCHAR(), nullable=True),
        sa.Column("webpage_url", sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("song")
    op.drop_table("radio")
    op.drop_table("playlistSong")
    op.drop_table("playlist")
    # ### end Alembic commands ###
