"""social credit

Revision ID: 298629fea1bc
Revises: 33ebe5556472
Create Date: 2022-06-09 18:37:42.362068

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "298629fea1bc"
down_revision = "33ebe5556472"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usercredit",
        sa.Column("id", sa.BIGINT, nullable=False),
        sa.Column("positives", sa.Integer(), nullable=True, default=0),
        sa.Column("negatives", sa.Integer(), nullable=True, default=0),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("usercredit")
    # ### end Alembic commands ###
