"""anilist_users

Revision ID: 32656ad0b5aa
Revises: 298629fea1bc
Create Date: 2023-02-27 11:59:09.458450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32656ad0b5aa'
down_revision = '298629fea1bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anilist_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('anilist_id', sa.Integer(), nullable=True),
    sa.Column('minutes_watched', sa.Integer(), nullable=True),
    sa.Column('chapters_read', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anilist_users')
    # ### end Alembic commands ###
