"""music init3

Revision ID: 715dd6656ed9
Revises: 79934200269d
Create Date: 2025-05-01 23:58:12.667147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '715dd6656ed9'
down_revision = '79934200269d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
