"""music init3

Revision ID: 79934200269d
Revises: 1b97a3238621
Create Date: 2025-05-01 23:57:14.073337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79934200269d'
down_revision = '1b97a3238621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radio', sa.Column('embed_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radio', 'embed_id')
    # ### end Alembic commands ###
