"""music init

Revision ID: a250f2cea9b1
Revises: 32656ad0b5aa
Create Date: 2025-05-01 22:14:15.639345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a250f2cea9b1'
down_revision = '32656ad0b5aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
