"""revision name

Revision ID: ab3711e19eb3
Revises: dd7c2d8c75a9
Create Date: 2025-05-02 17:55:38.914352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab3711e19eb3'
down_revision = 'dd7c2d8c75a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
