"""Added Stats to Anilist Table

Revision ID: c1913631e915
Revises: d8fb58840a71
Create Date: 2023-01-09 13:50:41.886145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1913631e915'
down_revision = 'd8fb58840a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anilist_users', sa.Column('minutes_watched', sa.Integer(), nullable=True))
    op.add_column('anilist_users', sa.Column('chapters_read', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anilist_users', 'chapters_read')
    op.drop_column('anilist_users', 'minutes_watched')
    # ### end Alembic commands ###
