"""removed playlist song mapping table constrain

Revision ID: dd7c2d8c75a9
Revises: 715dd6656ed9
Create Date: 2025-05-02 17:51:26.443628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd7c2d8c75a9'
down_revision = '715dd6656ed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
