# Bot Status
DATABASE_STATUS = "db_on"


# Social Credit
SOCIAL_CREDIT_ENABLE = "ENABLE_SOCIAL_CREDIT"
SOCIAL_CREDIT_UPVOTE = "UPVOTE_EMOJI_NAME"
SOCIAL_CREDIT_DOWNVOTE = "DOWNVOTE_EMOJI_NAME"
SOCIAL_CREDIT_WHITELIST = "SOCIAL_CREDIT_WHITELIST"
SOCIAL_CREDIT_TIMELIMIT = "SOCIAL_CREDIT_TIME_LIMIT"
